### ISSUE TITLE
Syntax error when trying to run script

### ISSUE THREAD

**Issue by larxene066** [cdgriffith/pi_streaming_setup#14]
On the latest commit. Here's the error:

`Syntax errors detected :
Line 43:
filename=f"streaming_setup_{datetime.datetime.now().strftime('%Y%M%d_%H%M%S')}.log",
SyntaxError: invalid syntax`

**Comment by cdgriffith** [comment]
Are you using Python 3?

**Comment by larxene066** [comment]
Yup!

**Comment by cdgriffith** [comment]
at least python 3.6? because I think it's barfing on the `f-string`

**Comment by larxene066** [comment]
I ended up making some changes and made it work myself. Thanks anyway!

**Comment by cdgriffith** [comment]
Glad to hear it's working. Did you have to remove the `f-string` or mess with the datetime to get it to work? I would like to fix the underlying issue if possible. Thanks!

**Comment by larxene066** [comment]
I replaced the f-string references. Not sure if it was an issue with my python version or not, either way I just brute-forced it to work for my setup. If others aren't experiencing issues, then I'm sure it was me. Cheers!
