### ISSUE TITLE
gpu_mem setting in /boot/config.txt

### ISSUE THREAD

**Issue by rezrov** [cdgriffith/pi_streaming_setup#15]
I had a chance to run the script (RTSP, compiling FFMPEG) on a freshly installed and updated Pi 3B+ and it ran like a champ, no errors. It took about an hour.

The service failed to start however, because I did not have enough memory assigned to the gpu for the camera I'm using. Bumping up the memory in /boot/config.txt fixed the issue.

```
[all]
gpu_mem=256
```

This might be outside the scope of your script, but the error messages I encountered gave no indication that gpu memory was the problem so it took some digging to figure it out. Perhaps a note about this in the README might save some people some time.

Thanks for your work on this project.

**Comment by cdgriffith** [comment]
Good point, I addressed that in [the article](https://codecalamity.com/raspberry-pi-hardware-accelerated-h264-webcam-security-camera/#real-time-encoding) but never linked / talked about here. 

Adding error message here in case someone googling / searching stumbles across this. 

> If at any point you receive the error ioctl(VIDIOC_STREAMON) failure : 1, Operation not permitted, go into raspi-config and up the video memory (memory split) to 256 and reboot.

**Comment by cdgriffith** [comment]
Adding to section in readme, thanks! https://github.com/cdgriffith/pi_streaming_setup#error-ioctlvidioc_streamon-failure--1-operation-not-permitted
