### ISSUE TITLE
Where are scripts installed to/ how to uninstall?

### ISSUE THREAD

**Issue by abishur** [cdgriffith/pi_streaming_setup#19]
I initially set this up using the rtsp option, but I'd like to change to another one.  How do I uninstall?

**Comment by cdgriffith** [comment]
First make sure to stop the service: `sudo systemctl stop stream_camera`  (if you re-install it will re-create / enable)

Then there are three files it may create: 

```
/var/lib/streaming/index.html
/var/lib/streaming/setup_streaming.sh
/etc/systemd/system/stream_camera.service
```

**Comment by abishur** [comment]
thanks!
