### ISSUE TITLE
simple-rtsp-server version string has changed

### ISSUE THREAD

**Issue by psaghelyi** [cdgriffith/pi_streaming_setup#20]
line 764-768

```
    mappings = {
        "armv7l": "armv7",
        "armv6l": "armv6",
        "aarch64": "arm64"
    }
```

please insert 'v' into arm version strings.

**Comment by cdgriffith** [comment]
Thanks for the heads up, fixed in https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.6.1
