### ISSUE TITLE
"Cannot iterate over bool", small mistake when using minimal flag

### ISSUE THREAD

**Issue by DiGatsby** [cdgriffith/pi_streaming_setup#21]
Line 365 in streaming_setup.py is

`for f, a in (all_ffmpeg_config if not minimal_install else minimal_install`

So nothing major to fix, correct is below

`for f, a in (all_ffmpeg_config if not minimal_install else minimal_ffmpeg_config`

**Comment by cdgriffith** [comment]
Thanks for the fix! https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.6.1
