### ISSUE TITLE
Cannot compile FFmpeg

### ISSUE THREAD

**Issue by vladtsit** [cdgriffith/pi_streaming_setup#24]
Hi, during compilation I'm getting following:
ERROR: OpenMAX IL headers from raspberrypi/firmware not found

how to correct?

Thanks,
Vladimir #

**Comment by cdgriffith** [comment]
That's a new one. 

Are you compiling this on a Raspberry Pi, and which model?
What OS and version are you running it on?

**Comment by vladtsit** [comment]
It was latest lite OS image for RPI3. Finally I was able to setup everything on legacy OS image, what is raspbian buster.
May be some incompatibilities with newest OS or other issues.

Thank you for great script!

**Comment by alingherghescu** [comment]
I want to confirm that I receive this error with latest raspbian 32bits when I tried to configure ffmpeg:

alin@raspberrypi:~/FFmpeg $ sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-libfreetype --enable-libx264 --enable-libmp3lame --enable-mmal --enable-indev=alsa --enable-outdev=alsa --extra-ldflags="-latomic"
ERROR: OpenMAX IL headers from raspberrypi/firmware not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
alin@raspberrypi:~/FFmpeg $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
alin@raspberrypi:~/FFmpeg $ uname -a
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
alin@raspberrypi:~/FFmpeg $ 

How to repro:
1. RPI4 8G
2. flashed 2022-04-04-raspios-bullseye-armhf-full.img.xz
3. apply all updates available (today: May 27, 2022)
4. applied the following steps:

compile ffmpeg with HW encoder:
sudo apt-get install libomxil-bellagio-dev libfreetype6-dev libmp3lame-dev checkinstall libx264-dev fonts-freefont-ttf libasound2-dev -y
cd ~
git clone https://github.com/FFmpeg/FFmpeg.git --depth 1
cd FFmpeg

sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-libfreetype --enable-libx264 --enable-libmp3lame --enable-mmal --enable-indev=alsa --enable-outdev=alsa --extra-ldflags="-latomic"

Let me know if you want me to run any tests/provide more data.
[config.log](https://github.com/cdgriffith/pi_streaming_setup/files/8790491/config.log)

Thank you,
Alin

**Comment by ert485** [comment]
> ERROR: OpenMAX IL headers from raspberrypi/firmware not found

I reached the same error, on a Pi Zero W with Raspberry Pi OS Debian 11 (bullseye) September 2022

Rather than downgrading the OS, I tried removing the omx options (omx seems to be deprecated, and v4l2m2m seems to be a good alternative):
I removed omx from [the configure options](https://github.com/cdgriffith/pi_streaming_setup/blob/master/streaming_setup.py#L63), and the compiled ffmpeg works great for my purposes using v4l2m2m

**Comment by cdgriffith** [comment]
Fixed in 1.7, thanks for the details! 

https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.7
