### ISSUE TITLE
ffmpeg openmax decode

### ISSUE THREAD

**Issue by shufayang** [cdgriffith/pi_streaming_setup#25]
Hello, every 01!
I want to implement the hard coding of openmax in ffmpeg, I modeled the encode frame to build the decode.  However, at the moment I have a problem, I don't know how to implement the **### omx_decode_frame** function

`static const AVClass omx_h264dec_class = {
    .class_name = "h264_decode_omx",
    .item_name  = av_default_item_name,
    .option     = options,
    .version    = LIBAVUTIL_VERSION_INT,
};
const FFCodec ff_h264_decode_omx_decoder = {
    .p.name           = "h264_decode_omx",
    .p.long_name      = NULL_IF_CONFIG_SMALL("OpenMAX IL H.264 video decoder"),
    .p.type           = AVMEDIA_TYPE_VIDEO,
    .p.id             = AV_CODEC_ID_H264,
    .priv_data_size   = sizeof(OMXCodecContext),
    .init             = omx_decode_init,
    FF_CODEC_ENCODE_CB(omx_decode_frame),
    .close            = omx_decode_end,
    .p.pix_fmts       = omx_decoder_pix_fmts,
    .p.capabilities   = AV_CODEC_CAP_DELAY,
    .caps_internal    = FF_CODEC_CAP_INIT_CLEANUP,
    .p.priv_class     = &omx_h264dec_class,
};`

Thanks!

**Comment by cdgriffith** [comment]
Hi @shufayang, as it seems almost a year later I don't think anyone here has that detailed of knowledge. I hope you were able to find some help elsewhere!
