### ISSUE TITLE
AviSynth can't find version.h

### ISSUE THREAD

**Issue by ert485** [cdgriffith/pi_streaming_setup#26]
When running the script, I hit the error:

> avisynth-build/version.h": No such file or directory.

That lead me to [an AviSynth issue](https://github.com/AviSynth/AviSynthPlus/issues/266) which describes that `VersionGen`  in `make VersionGen install` must now be explicitly included to get that file. 

I don't know what version.h is necessary for, but when I added `VersionGen` like above in the script, these steps completed successfully for me.

**Comment by cdgriffith** [comment]
Fixed in 1.7, thanks for the details! 

https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.7
