### ISSUE TITLE
zimg missing `graphengine/cpuinfo.cpp'`

### ISSUE THREAD

**Issue by ert485** [cdgriffith/pi_streaming_setup#27]
While the script was making zimg, I hit the following error:

> make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp',

More details and how another project fixed this issue: https://github.com/AnimMouse/ffmpeg-autobuild/issues/607

When cloning zimg, [`--recurse-submodules` should be included](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/f54926519d0cd2a39a63e194d5a1f4dcadc9aed8).

When I added this, the script was able to get to the next steps successfully.

**Comment by cdgriffith** [comment]
Fixed in 1.7, thanks for the details! 

https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.7
