### ISSUE TITLE
Could not find download for rtsp server

### ISSUE THREAD

**Issue by versamodule** [cdgriffith/pi_streaming_setup#28]
I get the following error when I run sudo python3 streaming_setup.py --rtsp
Any tips to fix ? 

Running On  a RPI CM4

P.S. thanks for showing us how to do this.

**Comment by FidelOdok** [comment]
Any solution to this

**Comment by cdgriffith** [comment]
Looks like the repo changed owners and names for execution files, I need to update to the new one https://github.com/bluenviron/mediamtx

**Comment by cdgriffith** [comment]
Fixed in 1.7, thanks for the details! 

https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.7
