### ISSUE TITLE
Script fails if /var/lib/streaming directory does not exist

### ISSUE THREAD

**Issue by rezrov** [cdgriffith/pi_streaming_setup#7]
install_rtsp() does not check that /var/lib/streaming exists before working with files in that directory.

Command executed:
```
sudo python3 streaming_setup.py --rtsp --compile-ffmpeg --run-as ron
```

**Comment by cdgriffith** [comment]
Fixed in [1.5.1](https://github.com/cdgriffith/pi_streaming_setup/releases/tag/1.5.1)

PR merged to master, apologizes again for delay due to not getting notifications!
