### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by K-a-R-e-N** [cdgriffith/pi_streaming_setup#9]
sudo python3 streaming_setup.py --rtsp

Starting streaming_setup 1.5.0
Using arguments: {'version': False, 'ffmpeg_command': False, 'device': '/dev/video0', 'video_size': '1920x1080', 'rtsp': True, 'rtsp_url': '', 'input_format': 'h264', 'codec': 'copy', 'ffmpeg_params': None, 'index_file': '/var/lib/streaming/index.html', 'on_reboot_file': '/var/lib/streaming/setup_streaming.sh', 'systemd_file': '/etc/systemd/system/stream_camera.service', 'compile_ffmpeg': False, 'camera_info': False, 'minimal': False, 'run_as': 'root', 'disable_fdk_aac': False, 'disable_avisynth': False, 'disable_dav1d': False, 'disable_zimg': False, 'disable_kvazaar': False, 'disable_libxavs': False, 'disable_libsrt': False, 'rebuild_all': False, 'safe': False}
ffmpeg already installed, skipping
Traceback (most recent call last):
  File "streaming_setup.py", line 877, in <module>
    main()
  File "streaming_setup.py", line 862, in main
    install_rtsp()
  File "streaming_setup.py", line 746, in install_rtsp
    rtsp_assets = json.dumps(urlopen(rtsp_releases[0]["assets_url"]).read().decode('utf-8'))
TypeError: string indices must be integers

**Comment by filipszu** [comment]
I get the same error.

**Comment by cdgriffith** [comment]
This issue should now be resolved in latest 1.5.1 thanks to @rezrov!
